# Generated by Django 4.1.4 on 2023-03-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essivi_sarl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
