# Generated by Django 4.1.4 on 2023-03-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essivi_sarl', '0002_commande_poids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='utilisateur_name',
            new_name='livreur_name',
        ),
    ]
